// This is an autogenerated file from Firebase Studio.

'use server';

/**
 * @fileOverview Suggests relevant tags for a fashion item based on its description and images.
 *
 * - suggestItemTags - A function that handles the tag suggestion process.
 * - SuggestItemTagsInput - The input type for the suggestItemTags function.
 * - SuggestItemTagsOutput - The return type for the suggestItemTags function.
 */

import {ai} from '@/ai/ai-instance';
import {z} from 'genkit';

const SuggestItemTagsInputSchema = z.object({
  description: z.string().describe('The description of the fashion item.'),
  imageUrl: z.string().describe('The URL of the fashion item image.'),
});
export type SuggestItemTagsInput = z.infer<typeof SuggestItemTagsInputSchema>;

const SuggestItemTagsOutputSchema = z.object({
  tags: z.array(
    z.string().describe('A relevant tag for the fashion item.')
  ).describe('The suggested tags for the fashion item.'),
});
export type SuggestItemTagsOutput = z.infer<typeof SuggestItemTagsOutputSchema>;

export async function suggestItemTags(input: SuggestItemTagsInput): Promise<SuggestItemTagsOutput> {
  return suggestItemTagsFlow(input);
}

const prompt = ai.definePrompt({
  name: 'suggestItemTagsPrompt',
  input: {
    schema: z.object({
      description: z.string().describe('The description of the fashion item.'),
      imageUrl: z.string().describe('The URL of the fashion item image.'),
    }),
  },
  output: {
    schema: z.object({
      tags: z.array(
        z.string().describe('A relevant tag for the fashion item.')
      ).describe('The suggested tags for the fashion item.'),
    }),
  },
  prompt: `You are a fashion expert. Suggest relevant tags for the following fashion item, based on its description and image. Only suggest tags that are relevant to the item.

Description: {{{description}}}
Image: {{media url=imageUrl}}

Tags:`,
});

const suggestItemTagsFlow = ai.defineFlow<
  typeof SuggestItemTagsInputSchema,
  typeof SuggestItemTagsOutputSchema
>({
  name: 'suggestItemTagsFlow',
  inputSchema: SuggestItemTagsInputSchema,
  outputSchema: SuggestItemTagsOutputSchema,
}, async input => {
  const {output} = await prompt(input);
  return output!;
});
